### ISSUE TITLE
`to close` should be `关闭`  In simplified Chinese

### ISSUE THREAD

**Issue by Alaye-Dong** [jooy2/vitepress-i18n#1]
Methods: generateI18nSearch.

In simplified Chinese, `to close` should be `关闭`, and `關閉` is traditional Chinese.🧐🥰

![image](https://github.com/user-attachments/assets/6092fd7f-0e83-45cb-92c2-51694f9dcf59)

**Comment by jooy2** [comment]
Hello! Thank you for reporting the issue. This issue has been fixed in version `1.1.1`. Thank you!
