### ISSUE TITLE
'editLink' will not work when using 'generateI18nLocale'

### ISSUE THREAD

**Issue by Alaye-Dong** [jooy2/vitepress-i18n#3]
**Describe the bug** A clear and concise description of what the bug is.

I used `generateI18nLocale ` in my project, but I found that `editLink `would fail. `editLink ` would be displayed as plain text and could not be clicked as a link.  The target generate language is set to `zhHans`.

```mts
  locales: generateI18nLocale({
    defineLocales: [
      { label: 'zhHans', translateLocale: 'zhHans' },
    ],
    rootLocale: 'zhHans',
  }),
```

![屏幕录制_2024-12-02_180313](https://github.com/user-attachments/assets/adb57987-87a2-4d8d-8e4a-f422e9d15afb)

I used the debugging tool and it showed that this web page element was empty and did not contain `href`.🤔

![179fb7237f1880b50e80eb717493e48c](https://github.com/user-attachments/assets/1ba0a054-ffb2-453b-962b-670da3558591)

When I commented out the code for `generateI18nLocale`, `editLink `works fine, so I think this should be a bug with `generateI18nLocale`. 🐞

Eager for a fix, thanks.🥰

**Desktop:**

- OS: [Windows 11]
- Browser [edge]

**Comment by jooy2** [comment]
Hello! Thank you for using `vitepress-i18n`.

First of all, i've made a lot of improvements in recent versions, which have drastically changed the usage and options.
I recommend that you use the latest version, and refer to the documentation on the page below to compare the changes:
https://vitepress-i18n.cdget.com/guide/getting-started

Based on the previous version, `editLink` can be applied via the `editLinkPattern` option, which is overridden by the themeConfig for each language.

In recent versions, the `editLinkPattern` option has been removed and should be used directly in `themeConfig`.
You can see an example of its use on the project documentation page:
https://github.com/jooy2/vitepress-i18n/blob/main/docs/.vitepress/config.ts#L89-L91

Regards,

**Comment by Alaye-Dong** [comment]
> Hello! Thank you for using `vitepress-i18n`.
> 
> First of all, i've made a lot of improvements in recent versions, which have drastically changed the usage and options. I recommend that you use the latest version, and refer to the documentation on the page below to compare the changes: https://vitepress-i18n.cdget.com/guide/getting-started
> 
> Based on the previous version, `editLink` can be applied via the `editLinkPattern` option, which is overridden by the themeConfig for each language.
> 
> In recent versions, the `editLinkPattern` option has been removed and should be used directly in `themeConfig`. You can see an example of its use on the project documentation page: https://github.com/jooy2/vitepress-i18n/blob/main/docs/.vitepress/config.ts#L89-L91
> 
> Regards,

After I upgraded `Vitepress-i18n` and modified its usage, `editLink `is back to normal, thanks！😊
